name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Skeleton, Fix SDK Versions, Icons & Build APK
        run: |
          # 1. Create Android skeleton files
          flutter create . --platforms=android --org com.ahm.booknotes

          # 2. Fix minSdk to 21 and compileSdk to 34 directly in build.gradle
          python3 -c "
          p = 'android/app/build.gradle'
          with open(p, 'r') as f:
              c = f.read()
          c = c.replace('compileSdkVersion flutter.compileSdkVersion', 'compileSdkVersion 34')
          c = c.replace('compileSdk = flutter.compileSdkVersion', 'compileSdk = 34')
          c = c.replace('minSdkVersion flutter.minSdkVersion', 'minSdkVersion 21')
          c = c.replace('minSdk = flutter.minSdkVersion', 'minSdk = 21')
          c = c.replace('targetSdkVersion flutter.targetSdkVersion', 'targetSdkVersion 34')
          c = c.replace('targetSdk = flutter.targetSdkVersion', 'targetSdk = 34')
          with open(p, 'w') as f:
              f.write(c)
          "

          # 3. Get dependencies
          flutter pub get

          # 4. Generate app launcher icons
          dart run flutter_launcher_icons

          # 5. Set App Display Name
          sed -i 's/android:label=".*"/android:label="BookNotes"/g' android/app/src/main/AndroidManifest.xml

          # 6. Build Universal APK
          flutter build apk --release --target-platform android-arm,android-arm64,android-x64

      - name: Upload Universal Release APK
        uses: actions/upload-artifact@v4
        with:
          name: BookNotes-Universal-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
